---
- hosts: servers
  become: true
  tasks:
    - name: Install packages
      yum:
        name: "apache2"
        state: "present"
    - name: start apache server
      service:
        name: httpd
        state: started 
        enabled: true 
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
